myproject/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logged_out.html'}, name='logout'),
    url(r'^register/$', 'accounts.views.register', name='register'),
)

myproject/myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from myproject import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^creatures/', include('creatures.urls', namespace="creatures")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

#    url(r'^login/$', 'django.contrib.auth.views.login'),
#    url(r'^logout/$', 'django.contrib.auth.views.logout'),
#    url(r'^register/$', 'creatures.views.register'),

)

myproject/templates/base.html
{% load staticfiles %}
<html>
    <head>

    {% block scripts %}    
    {% endblock %}

    {% block head %}    
    {% endblock %}


    </head>

    <body>
        <div style="text-align: right; height: 50px; width: 100%;">
            {{ user }}
            {% if user.is_anonymous %}
            <a href="{% url 'accounts:django.contrib.auth.views.login' %}">Login</a> | 
            <a href="{% url 'accounts:register' %}">Register</a>
            
            {% else %}
            {{ user.name }} <a href="{% url 'accounts:django.contrib.auth.views.logout' %}">Logout</a>
            {% endif %}

        </div>
        {% block content %}
        {% endblock %}

    
    </body>
</html>

myproject/templates/index.html
{% extends "base.html" %}

{% block content %}
{% if user.is_anonymous %}
<a href="{% url 'accounts:register' %}">Register</a> or <a href="{% url 'accounts:django.contrib.auth.views.login' %}">login</a> to visit your <a href="{% url 'creatures:index' %}">Creatures</a>.
{% endif %}
{% if not user.is_anonymous %}
View your <a href="{% url 'creatures:index' %}">Creatures</a>.
{% endif %}
{% endblock %}