myproject/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logged_out.html'}, name='logout'),
    url(r'^register/$', 'accounts.views.register', name='register'),
)

myproject/creatures/urls.py
from django.conf.urls import patterns, url
from creatures import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<creature_id>\d+)/$', views.cdetail, name='creature_detail'),
    url(r'^fight/$', views.cfight, name='fight'),
    url(r'^create/$', views.create, name='create'),
    url(r'^make/$', views.make, name='make'),
    url(r'^(?P<creature_id>\d+)/delete/$', views.delete, name='creature_delete'),
    url(r'^(?P<creature_id>\d+)/(?P<evolution_id>\d+)/buy/$', views.buy, name='buy_evo'),
    
)

myproject/myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from myproject import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^creatures/', include('creatures.urls', namespace="creatures")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

#    url(r'^login/$', 'django.contrib.auth.views.login'),
#    url(r'^logout/$', 'django.contrib.auth.views.logout'),
#    url(r'^register/$', 'creatures.views.register'),

)

myproject/creatures/models.py
from django.db import models
from django.shortcuts import get_object_or_404

class Creature(models.Model):
    name = models.CharField(max_length=20)
    evp_earned = models.IntegerField(default=0)
    evp_spent = models.IntegerField(default=0)
    atk_power = models.IntegerField(default=6)
    armor = models.IntegerField(default=0)
    constitution = models.IntegerField(default=0)
    crit_bonus = models.IntegerField(default=0)
    health = models.IntegerField(default=45)
    dodge = models.IntegerField(default=0)
    accuracy = models.IntegerField(default=0)
    evolutions = models.ManyToManyField('Evolution', blank=True)
    ability1 = models.ForeignKey('Ability', related_name='ability1', blank=True, null=True)
    ability2 = models.ForeignKey('Ability', related_name='ability2', blank=True, null=True)
    ability3 = models.ForeignKey('Ability', related_name='ability3', blank=True, null=True)

    def __unicode__(self):
        return self.name

# This updates a creature based on their evolutions, since we don't store evolved stats in the database
    def evolve(creature):
        creature.atk_power = 0
        creature.armor = 0
        creature.constitution = 0
        creature.crit_bonus = 0
        creature.health = 0
        creature.dodge = 0
        creature.accuracy = 0
        for e in creature.evolutions.all():
            creature.atk_power = creature.atk_power + e.atk_power 
            creature.armor = creature.armor + e.armor
            creature.constitution = creature.constitution + e.constitution
            creature.crit_bonus = creature.crit_bonus + e.crit_bonus
            creature.health = creature.health + e.health
            creature.dodge = creature.dodge + e.dodge
            creature.accuracy = creature.accuracy + e.accuracy
        if get_object_or_404(Evolution, name="Venom Sacs") in creature.evolutions.all():
            creature.ability2 = (get_object_or_404(Ability, name="spit"))
            creature.save(update_fields=['ability2'])

        return creature


class Evolution(models.Model):
    name = models.CharField(max_length=100)
    cost = models.IntegerField(default=0)
    desc = models.CharField(max_length=2000)
    atk_power = models.IntegerField(default=0)
    armor = models.IntegerField(default=0)
    constitution = models.IntegerField(default=0)
    crit_bonus = models.IntegerField(default=0)
    health = models.IntegerField(default=0)
    dodge = models.IntegerField(default=0)
    accuracy = models.IntegerField(default=0)
    exclusive_with = models.ManyToManyField('self', blank=True)
    requires = models.ManyToManyField('self', blank=True)
    req_evp_spent = models.IntegerField(default=0)
        
    def __unicode__(self):
        return self.name

class Ability(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=2000)
    combat_string = models.CharField(max_length=1000)
    damage_choices = (
        ('Physical', 'Physical'),
        ('Elemental', 'Elemental'),
        ('Non-damaging', 'Non-damaging'),
        )
    damage_type = models.CharField(max_length=100, choices=damage_choices, blank=False, default='Physical')
    ability_slot = models.IntegerField(default=1)
    # Maybe ManyToMany to an 'Effect' class for buffs/debuffs
        
    def __unicode__(self):
        return self.name

myproject/creatures/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from creatures.models import Creature, Ability, Evolution
from accounts.models import Account
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
import fight, evolve
import urllib2
from django.contrib.auth.decorators import login_required

@login_required
def index(request):

    # delete HPs from session if you retreat to the stable at any point
    try:
        del request.session['creature1']
    except KeyError:
        pass
    try:
        del request.session['creature2']
    except KeyError:
        pass
    try:
        del request.session['creature3']
    except KeyError:
        pass
    try:
        del request.session['enemy']
        print "Deleted enemy health from session"
    except KeyError:
        pass


    account_number = request.user.id
    your_creatures_list = Creature.objects.filter(account=account_number)
    empty_slot = False
    if len(your_creatures_list) < 10:
        empty_slot = True

    #get list of creatures that are in team
    player = Account.objects.get(user=request.user)
    team = player.team.all()

    enemies_list = Creature.objects.filter(account=None)


    context = {'your_creatures_list': your_creatures_list, 'empty_slot': empty_slot, 'team': team, 'enemies_list': enemies_list}
    return render(request, 'creatures/index.html', context)

def cdetail(request, creature_id):
    creature = get_object_or_404(Creature, pk=creature_id)
    evp_left = creature.evp_earned - creature.evp_spent
    evolved_creature = creature.evolve()
    available_evolutions = evolve.allowed_evos(creature)
    affordable_evolutions = []
    for e in available_evolutions:
        if creature.evp_earned - creature.evp_spent > e.cost:
            affordable_evolutions.append(e)

        
    return render(request, 'creatures/cdetail.html', {'creature': evolved_creature, 'available_evolutions': available_evolutions, 'evp_left': evp_left, 'affordable_evolutions': affordable_evolutions})

@login_required
def buy(request, creature_id, evolution_id):
    creature = get_object_or_404(Creature, id=creature_id)
    bought_evo = get_object_or_404(Evolution, id=evolution_id)
    canpay = False
    available_evolutions = evolve.allowed_evos(creature)
    if creature.evp_earned - creature.evp_spent > bought_evo.cost:
        canpay = True
    if canpay == True and bought_evo in available_evolutions:
        creature.evolutions.add(bought_evo)
        creature.evp_earned = creature.evp_earned - bought_evo.cost
        creature.save()
        url = reverse('creatures:creature_detail', args=[creature.id])
        return HttpResponseRedirect(url)
    else:
        return HttpResponse("You can't buy that.")

@login_required
def create(request): 
    return render(request, 'creatures/create.html', {'user': request.user})

@login_required
def make(request):
    body_choice = request.POST['body']
    if body_choice == 'rabbit':
        evos = [get_object_or_404(Evolution, name='Rabbit Form'), get_object_or_404(Evolution, name='Trainer\'s Gift')]
        abil = get_object_or_404(Ability, name='bite')
    elif body_choice == 'lizard':
        evos = [get_object_or_404(Evolution, name='Lizard Form'), get_object_or_404(Evolution, name='Trainer\'s Gift')]
        abil = get_object_or_404(Ability, name='bite')
    else:
        evos = [get_object_or_404(Evolution, name='Scorpion Form'), get_object_or_404(Evolution, name='Trainer\'s Gift')]
        abil = get_object_or_404(Ability, name='sting')
    made_creature = Creature(name=request.POST['name'], ability1=abil)
    made_creature.save()
    made_creature.evolutions.add(*evos) # * unpacks list for add function
    owner = Account.objects.get(user=request.user)
    owner.creatures.add(made_creature)
    return HttpResponseRedirect(reverse('creatures:index'))
# These next two lines are equivalent ways to return the name of creatures owned by the current user.
#    return HttpResponse(Creature.objects.filter(account=request.user.id))
#    return HttpResponse(Account.objects.get(user=request.user).creatures.all())

@login_required
def delete(request, creature_id):
    Creature.objects.filter(id=creature_id).delete()
    return HttpResponseRedirect(reverse('creatures:index'))

@login_required
def cfight(request):
    team = []
    player = Account.objects.get(user=request.user)
    earned = 0
    # Get creature team ids from POST
    if 'team_1' in request.POST or 'team_2' in request.POST or 'team_3' in request.POST:
        player.team.clear()
        team = []
        print "team variable just cleared"
        if 'team_1' in request.POST:
            try:
                team.append(get_object_or_404(Creature, id=request.POST.get("team_1")))
            except urllib2.HTTPError as err:
                if err.code == 404:
                   pass
                else:
                   raise
            except ValueError:
                pass

        if 'team_2' in request.POST:
            try:
                team.append(get_object_or_404(Creature, id=request.POST.get("team_2")))
            except urllib2.HTTPError as err:
                if err.code == 404:
                   pass
                else:
                   raise
            except ValueError:
                pass

        if 'team_3' in request.POST:
            try:
                team.append(get_object_or_404(Creature, id=request.POST.get("team_3")))
            except urllib2.HTTPError as err:
                if err.code == 404:
                   pass
                else:
                   raise
            except ValueError:
                pass


        player.team.add(*team)
        if len(team) <= 0:
            return HttpResponseRedirect(reverse('creatures:index'))
       
    print "adding to pcreatures", player, team
    pcreatures = player.team.all()
    print pcreatures
    # Get enemy out of POST if it is there and save to session
    # Otherwise get it from session or use a default
    if 'enemy' in request.POST:
        enemy = get_object_or_404(Creature, id=request.POST.get("enemy")).evolve()
        request.session['enemy_id'] = enemy.id

    elif request.session.get('enemy_id'):
        print "from session get enemy with id =", request.session.get('enemy_id')
        enemy = get_object_or_404(Creature, id=request.session.get('enemy_id')).evolve()

    else:
        enemy = get_object_or_404(Creature, name="EnemyScorpion").evolve()

    MatchDone = None

    
    # Get healths from session and see if anyone is alive
    total_health_left = 0
    cnum = 1
    for c in pcreatures:
        c = c.evolve()
        c.health_left = 0
        if request.session.get('creature'+str(cnum)):
            c.health_left = request.session.get('creature'+str(cnum))["health_left"]
            print c.name, "had health in session:", c.health_left
        cnum = cnum + 1
        total_health_left = total_health_left + max(c.health_left, 0)


    enemy.health_left = 0
    if request.session.get('enemy'):
        enemy.health_left = request.session.get('enemy')["health_left"]
    print "total_health before combat:", total_health_left



    # if both teams aren't alive in a session, start a fresh one
    if not total_health_left > 0 or not enemy.health_left > 0:
        print 'start new session'
        for cnum in range(0, 3):
            try:
                del request.session['creature'+str(cnum)]
            except KeyError:
                pass


        cnum = 1
        for c in pcreatures:
            c.health_left = c.health
            request.session['creature'+str(cnum)] = {'health_left': c.health_left}
            cnum += 1

        total_health_left = 0 #recalculate t_h_l for new session
        for c in pcreatures:
            total_health_left = total_health_left + max(c.health_left, 0)


        enemy.health_left = enemy.health
        request.session['enemy'] = {'health_left': enemy.health_left}      


    # choose the current combatant
    current = fight.current(pcreatures)


    
    # Use player's chosen attack
    result = None
    if request.method=='POST':
        if not 'team1' in request.POST:
            if 'ability1' in request.POST:
                result = fight.combat(current, current.ability1, enemy)
            elif 'ability2' in request.POST:
                result = fight.combat(current, current.ability2, enemy)
            elif 'ability3' in request.POST:
                result = fight.combat(current, current.ability3, enemy)

            # After attack, save new health_left values to session
            # This is dumb, I can't name session value after the creature
            # because I won't know how to clear them if user changes the team.
            # But since names are generic, I can't update just one creature.
            cnum = 1
            total_health_left = 0
            for c in pcreatures:
                total_health_left = total_health_left + max(c.health_left, 0)
                request.session['creature'+str(cnum)] = {'health_left': c.health_left}
                print "updated HP after attack:", c.name, cnum, request.session['creature'+str(cnum)]
                cnum = cnum + 1


            request.session['enemy'] = {'health_left': enemy.health_left}




    # If one team is dead, end fight
    if enemy.health_left <= 0:
        MatchDone = 'Victory'
    elif total_health_left <= 0:
        MatchDone = 'Defeat'
    print MatchDone



    # if a pcreature died, and replacement steps in, mention it
    if current.health_left <= 0:
        if fight.current(pcreatures) != None:
            result[1] =  ' '.join([result[1], fight.current(pcreatures).name, 'steps up to fight.'])
    
    # update the current combatant in case one died
    current = fight.current(pcreatures)

myproject/creatures/templates/creatures/cdetail.html
{% extends "base.html" %}
{% block content %}
<style>
* {
    font-size: 10pt;
}

span:hover {
    background-color:white !important;
    color:black !important;
    }

</style>


<h1>{{ creature }}</h1>
<p><strong>Combat Stats:</strong><br>
{{ creature.health }} Health Points.<br>
{{ creature.atk_power }} Attack Power.<br>
{{ creature.crit_bonus }} Critical Bonus (extra damage on critical hits).<br>
{{ creature.armor }} Armor (reduced damage from physical attacks).<br>
{{ creature.constitution }} Constitution (reduced damage from elemental attacks).<br>
{{ creature.dodge }} Dodge (damage taken reduced on dodge).<br>
{{ creature.accuracy }} Accuracy (enemy dodge negated).<br>
</p>

<p><strong>Combat Abilities:</strong><br>
{% if creature.ability1 %}<em>{{ creature.ability1 }}</em> - {{ creature.ability1.desc }}<br>{% endif %}
{% if creature.ability2 %}<em>{{ creature.ability2 }}</em> - {{ creature.ability2.desc }}<br>{% endif %}
{% if creature.ability3 %}<em>{{ creature.ability3 }}</em> - {{ creature.ability3.desc }}<br>{% endif %}
</p>


<p><strong>Active Evolutions:</strong><br>
<ul>
{% for e in creature.evolutions.all %}
    <li><strong>{{ e.name }}</strong><br>
    {{ e.desc }}<br>
    {% if e.atk_power %}Attack Power: +{{ e.atk_power }},   {% endif %}
    {% if e.crit_bonus %}Crit Bonus: +{{ e.crit_bonus }},   {% endif %}
    {% if e.accuracy %}Accuracy: +{{ e.accuracy }},   {% endif %}
    {% if e.health %}Health: +{{ e.health }},   {% endif %}
    {% if e.armor %}Armor: +{{ e.armor }},   {% endif %}
    {% if e.constitution %}Constitution: +{{ e.constitution }},   {% endif %}
    {% if e.dodge %}Dodge: +{{ e.dodge }},   {% endif %}
    </li><br>
{% endfor %}
</ul>
</p>

<p><strong>Available Evolutions:</strong><br>
{{ evp_left }} Evolution Points (EVP) available.<br>

{% for e in available_evolutions %}
<div style="border: 1px solid gray; float: left; width: 600px; border-radius: 5px; padding: 5px; margin: 5px; background: ivory;">
<strong>{{ e.name }}</strong> (cost: {{ e.cost }} EVP) 

    {% if e in affordable_evolutions %}<a style="text-decoration: none;" href="{% url 'creatures:buy_evo' creature.id e.id %}"><span class="buybut" style="background: orange; padding: 1px; border-radius: 2px; color: white; border: 1px solid darkorange; font-size: 9pt;"><strong>BUY</strong></a>{% endif %}<br>
    {{ e.desc }}<br>
    {% if e.atk_power %}Attack Power: +{{ e.atk_power }},   {% endif %}
    {% if e.crit_bonus %}Crit Bonus: +{{ e.crit_bonus }},   {% endif %}
    {% if e.accuracy %}Accuracy: +{{ e.accuracy }},   {% endif %}
    {% if e.health %}Health: +{{ e.health }},   {% endif %}
    {% if e.armor %}Armor: +{{ e.armor }},   {% endif %}
    {% if e.constitution %}Constitution: +{{ e.constitution }},   {% endif %}
    {% if e.dodge %}Dodge: +{{ e.dodge }},   {% endif %}
    <br><br>
    {% if e.requires.all %}<em>Requires:</em> {% for r in e.requires.all %}{{ r.name }}{% endfor %}<br>{% endif %}
    {% if e.exclusive_with.all %}<em>Exclusive with:</em> {% for r in e.exclusive_with.all %}{{ r.name }}{% endfor %}{% endif %}
</div><br>

{% endfor %}

{% if creature.evp_earned > 0 %}

{% endif %}


{% endblock %}

myproject/creatures/templates/creatures/create.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p>{{ error_message }}</p>{% endif %}
    <h1>{{ user }}'s New Creature:</h1>
    <form action="{% url 'creatures:make' %}" method="post">
    {% csrf_token %}

    <input type="text" name="name" id="name" value="" />
    <br><label for="name">Name</label><br>

    <p><strong>Base Form:</strong></p>
    <input type="radio" name="body" id="body1" value="rabbit" />
    <label for="body1">Rabbit (+5 Dodge)</label><br>
    <input type="radio" name="body" id="body2" value="lizard" />
    <label for="body2">Lizard - (+1 Armor)</label><br>
    <input type="radio" name="body" id="body3" value="scorpion" />
    <label for="body3">Scorpion - (+1 Resist. Primary attack does poison damage.)</label><br>


    <br /><input type="submit" value="Create Creature" />
    </form>
    
    

{% endblock %}

myproject/creatures/templates/creatures/fight.html
{% extends "base.html" %}

{% block content %}


<div style="float: left; width: 40%">
{% if current %}
<strong>{{ current.name }}</strong> ({{ current.health_left }}/{{ current.health }} HP)<br>
{% endif %}

<form action="{% url 'creatures:fight' %}" method="post">
{% csrf_token %}

{% if matchdone == None %}
<div>
{% if current.ability1 %}<input type="submit" name="ability1" value="{{ current.ability1 }}"/>{% endif %}

{% if current.ability2 %}<input type="submit" name="ability2" value="{{ current.ability2 }}"/>{% endif %}

{% if current.ability3 %}<input type="submit" name="ability3" value="{{ current.ability3 }}"/>{% endif %}
</div><br>
{% endif %}

{% if matchdone == 'Victory' %}
<p>You won! Each member of your combat team earned {{ earned }} Evolution Points! <a href="{% url 'creatures:index' %}">Return to your stable.</a></p>
{% endif %}

{% if matchdone == 'Defeat' %}
<p>You lost. <a href="{% url 'creatures:index' %}">Return to your stable.</a></p>
{% endif %}

</div>

<div style="width: 10%; float: left; text-align: center;">
-vs-
</div>

<div style="float: left;">
<strong>{{ enemy.name }}</strong> ({{ enemy.health_left }}/{{ enemy.health }} HP)<br>
Your CPU-controlled opponent.
</div>


{% if result %}
<div style="width: 90%; height: auto; margin-top: 30px; border: 1px solid gray; float: left;">
<div style="width: 100%; border-bottom: 1px solid gray; text-align: center;">
Combat Log (last round)
</div>
<p>{{ result.0 | safe }}</p>
<p>{{ result.1 | safe }}</p>
</div>
{% endif %}


{% endblock %}

myproject/creatures/templates/creatures/index.html
{% extends "base.html" %}

{% block scripts %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" ></script>
<script>
$(document).ready(function () {
    $("select").change(function () {
        var $this = $(this);
        var prevVal = $this.data("prev");
        var otherSelects = $("select").not(this);
        var val = $(this).find('option:selected').val();

        if (prevVal) {
            otherSelects.find("option[value=" + prevVal + "]").attr('disabled', false);
        }

        $this.data("prev", $this.val());
        if (!val) return;
        otherSelects.find("option[value=" + $(this).val() + "]").attr('disabled', true);
    });
});
</script>

<script>

</script>


{% endblock %}

{% block content %}
<div id="content_wrap" style="width: 90%; padding: 30px; float: left;">

<div id="team" style= "float: left;">
<strong>Combat Team</strong>
<form action="{% url 'creatures:fight' %}" method="post">
{% csrf_token %}

<select name="team_1" id="team_1" class="selbox">
<option value=""></option>
{% for creature in your_creatures_list %}
<option {% if creature == team.0 %}selected = "selected" {% endif %}value="{{ creature.id }}">{{ creature.name }}</option>
{% endfor %}
</select><br>
<select name="team_2" id="team_2" class="selbox">
<option value=""></option>
{% for creature in your_creatures_list %}
<option {% if creature == team.1 %}selected = "selected" {% endif %}value="{{ creature.id }}">{{ creature.name }}</option>
{% endfor %}
</select><br>
<select name="team_3" id="team_3" class="selbox">
<option value=""></option>
{% for creature in your_creatures_list %}
<option {% if creature == team.2 %}selected = "selected" {% endif %}value="{{ creature.id }}">{{ creature.name }}</option>
{% endfor %}
</select><br>
<br>
<strong>Select Enemy</strong>
<br>
{% for enemy in enemies_list %}
<input type="radio" name="enemy" id="{{ enemy.name }}" value="{{ enemy.id }}" />
<label for="{{ enemy.name }}"><a href="{% url 'creatures:creature_detail' enemy.id %}">{{ enemy.name }}</a></label><br>
{% endfor %}



<p><input type="submit" value="Send Team To Battle" style="background: orange;" /></p>
</form>
</div>

<div id="stable" style="float: right;">
<strong>Your Creatures:</strong>
    <ol>
    {% for creature in your_creatures_list %}
        <li>
        <a href="{% url 'creatures:creature_detail' creature.id %}">{{ creature.name }}</a>
        <a href="{% url 'creatures:creature_delete' creature.id %}">(delete)</a>
        </li>
    {% endfor %}
    {% if empty_slot %}
        <li><a href="{% url 'creatures:create' %}">Create a new creature</a></li>
    {% endif %}
    </ul>
</div>

</div>
{% endblock %}